import 'package:practice/models/models.dart';

class MockBackend {
  // Equipment available with hourly and daily rates
  static List<Equipment> availableHourlyEquipment = [
    Equipment(name: 'Projector', hourlyRate: 15.0, dailyRate: 0.0),
    Equipment(
        name: 'Camera',
        hourlyRate: 30.0,
        dailyRate: 0.0), // Additional equipment
    Equipment(
        name: 'Laptop',
        hourlyRate: 15.0,
        dailyRate: 0.0), // Additional equipment
  ];

  static List<Equipment> availableDailyEquipment = [
    Equipment(name: 'Stage', hourlyRate: 0.0, dailyRate: 500.0),
    Equipment(
        name: 'Audience chairs non cushioned',
        hourlyRate: 0.0,
        dailyRate: 10.0),
    Equipment(
        name: 'Audience chairs cushioned', hourlyRate: 0.0, dailyRate: 20.0),
    Equipment(name: 'VIP Chairs', hourlyRate: 0.0, dailyRate: 50.0),
    Equipment(name: 'Sofa', hourlyRate: 0.0, dailyRate: 150.0),
    Equipment(name: 'Deepak Stand', hourlyRate: 0.0, dailyRate: 25.0),
    Equipment(name: 'Center table', hourlyRate: 0.0, dailyRate: 30.0),
    Equipment(name: 'Rectangle table', hourlyRate: 0.0, dailyRate: 40.0),
    Equipment(name: 'Round tables', hourlyRate: 0.0, dailyRate: 35.0),
    Equipment(name: 'Flowers', hourlyRate: 0.0, dailyRate: 15.0),
    Equipment(
        name: 'Flowerpots with flowers', hourlyRate: 0.0, dailyRate: 12.0),
    Equipment(name: 'Flower decoration', hourlyRate: 0.0, dailyRate: 25.0),
    Equipment(name: 'Bokeh', hourlyRate: 0.0, dailyRate: 20.0),
    Equipment(name: 'Wrapped roses', hourlyRate: 0.0, dailyRate: 18.0),
    Equipment(name: 'Flowers bunch', hourlyRate: 0.0, dailyRate: 22.0),
    Equipment(name: 'Red carpet', hourlyRate: 0.0, dailyRate: 100.0),
    Equipment(name: 'Floor carpet', hourlyRate: 0.0, dailyRate: 80.0),
    Equipment(name: 'Transport (Goods)', hourlyRate: 0.0, dailyRate: 250.0),
    Equipment(name: 'Transport (Passenger)', hourlyRate: 0.0, dailyRate: 300.0),
  ];

  // Vendor prices for the equipment (assuming the price is per unit)
  static Map<String, Map<String, double>> vendorPrices = {
    'vendor_1': {
      'Projector': 15.0,
      'Camera': 30.0,
      'Laptop': 15.0,
      'Stage': 500.0,
      'Audience chairs non cushioned': 10.0,
      'Audience chairs cushioned': 20.0,
      'VIP Chairs': 50.0,
      'Sofa': 150.0,
      'Deepak Stand': 25.0,
      'Center table': 30.0,
      'Rectangle table': 40.0,
      'Round tables': 35.0,
      'Flowers': 15.0,
      'Flowerpots with flowers': 12.0,
      'Flower decoration': 25.0,
      'Bokeh': 20.0,
      'Wrapped roses': 18.0,
      'Flowers bunch': 22.0,
      'Red carpet': 100.0,
      'Floor carpet': 80.0,
      'Transport (Goods)': 250.0,
      'Transport (Passenger)': 300.0,
    },
    'vendor_2': {
      'Projector': 18.0,
      'Camera': 35.0,
      'Laptop': 20.0,
      'Stage': 550.0,
      'Audience chairs non cushioned': 12.0,
      'Audience chairs cushioned': 25.0,
      'VIP Chairs': 55.0,
      'Sofa': 160.0,
      'Deepak Stand': 30.0,
      'Center table': 35.0,
      'Rectangle table': 45.0,
      'Round tables': 40.0,
      'Flowers': 18.0,
      'Flowerpots with flowers': 15.0,
      'Flower decoration': 28.0,
      'Bokeh': 22.0,
      'Wrapped roses': 20.0,
      'Flowers bunch': 25.0,
      'Red carpet': 110.0,
      'Floor carpet': 90.0,
      'Transport (Goods)': 270.0,
      'Transport (Passenger)': 320.0,
    },
    'vendor_3': {
      'Projector': 12.0,
      'Camera': 28.0,
      'Laptop': 12.0,
      'Stage': 480.0,
      'Audience chairs non cushioned': 8.0,
      'Audience chairs cushioned': 18.0,
      'VIP Chairs': 45.0,
      'Sofa': 140.0,
      'Deepak Stand': 22.0,
      'Center table': 28.0,
      'Rectangle table': 38.0,
      'Round tables': 33.0,
      'Flowers': 12.0,
      'Flowerpots with flowers': 10.0,
      'Flower decoration': 20.0,
      'Bokeh': 18.0,
      'Wrapped roses': 16.0,
      'Flowers bunch': 20.0,
      'Red carpet': 90.0,
      'Floor carpet': 70.0,
      'Transport (Goods)': 240.0,
      'Transport (Passenger)': 290.0,
    },
    'vendor_4': {
      'Projector': 20.0,
      'Camera': 32.0,
      'Laptop': 18.0,
      'Stage': 520.0,
      'Audience chairs non cushioned': 11.0,
      'Audience chairs cushioned': 22.0,
      'VIP Chairs': 48.0,
      'Sofa': 155.0,
      'Deepak Stand': 27.0,
      'Center table': 33.0,
      'Rectangle table': 42.0,
      'Round tables': 37.0,
      'Flowers': 16.0,
      'Flowerpots with flowers': 14.0,
      'Flower decoration': 26.0,
      'Bokeh': 21.0,
      'Wrapped roses': 19.0,
      'Flowers bunch': 23.0,
      'Red carpet': 105.0,
      'Floor carpet': 85.0,
      'Transport (Goods)': 260.0,
      'Transport (Passenger)': 310.0,
    },
    'vendor_5': {
      'Projector': 14.0,
      'Camera': 29.0,
      'Laptop': 16.0,
      'Stage': 490.0,
      'Audience chairs non cushioned': 9.0,
      'Audience chairs cushioned': 21.0,
      'VIP Chairs': 52.0,
      'Sofa': 145.0,
      'Deepak Stand': 24.0,
      'Center table': 32.0,
      'Rectangle table': 39.0,
      'Round tables': 34.0,
      'Flowers': 14.0,
      'Flowerpots with flowers': 11.0,
      'Flower decoration': 22.0,
      'Bokeh': 19.0,
      'Wrapped roses': 17.0,
      'Flowers bunch': 21.0,
      'Red carpet': 95.0,
      'Floor carpet': 75.0,
      'Transport (Goods)': 245.0,
      'Transport (Passenger)': 305.0,
    },
    'vendor_6': {
      'Projector': 17.0,
      'Camera': 34.0,
      'Laptop': 17.0,
      'Stage': 510.0,
      'Audience chairs non cushioned': 10.0,
      'Audience chairs cushioned': 23.0,
      'VIP Chairs': 53.0,
      'Sofa': 165.0,
      'Deepak Stand': 29.0,
      'Center table': 31.0,
      'Rectangle table': 41.0,
      'Round tables': 36.0,
      'Flowers': 17.0,
      'Flowerpots with flowers': 13.0,
      'Flower decoration': 27.0,
      'Bokeh': 23.0,
      'Wrapped roses': 21.0,
      'Flowers bunch': 24.0,
      'Red carpet': 115.0,
      'Floor carpet': 95.0,
      'Transport (Goods)': 275.0,
      'Transport (Passenger)': 325.0,
    },
    'vendor_7': {
      'Projector': 19.0,
      'Camera': 36.0,
      'Laptop': 19.0,
      'Stage': 530.0,
      'Audience chairs non cushioned': 12.0,
      'Audience chairs cushioned': 24.0,
      'VIP Chairs': 50.0,
      'Sofa': 160.0,
      'Deepak Stand': 28.0,
      'Center table': 30.0,
      'Rectangle table': 44.0,
      'Round tables': 39.0,
      'Flowers': 20.0,
      'Flowerpots with flowers': 16.0,
      'Flower decoration': 30.0,
      'Bokeh': 25.0,
      'Wrapped roses': 22.0,
      'Flowers bunch': 26.0,
      'Red carpet': 120.0,
      'Floor carpet': 100.0,
      'Transport (Goods)': 280.0,
      'Transport (Passenger)': 330.0,
    },
    'vendor_8': {
      'Projector': 16.0,
      'Camera': 33.0,
      'Laptop': 14.0,
      'Stage': 540.0,
      'Audience chairs non cushioned': 13.0,
      'Audience chairs cushioned': 25.0,
      'VIP Chairs': 47.0,
      'Sofa': 150.0,
      'Deepak Stand': 26.0,
      'Center table': 29.0,
      'Rectangle table': 37.0,
      'Round tables': 32.0,
      'Flowers': 13.0,
      'Flowerpots with flowers': 12.0,
      'Flower decoration': 24.0,
      'Bokeh': 20.0,
      'Wrapped roses': 18.0,
      'Flowers bunch': 21.0,
      'Red carpet': 110.0,
      'Floor carpet': 85.0,
      'Transport (Goods)': 260.0,
      'Transport (Passenger)': 315.0,
    },
  };
}
