import 'package:practice/models/models.dart';

class MockBackend {
  // Simulated vendor pricing
  static Map<String, Map<String, double>> vendorPrices = {
    'vendor_1': {
      'Podium': 100.0,
      'Mic and Sound System': 200.0,
      'Stage': 500.0,
      'Audience chairs non cushioned': 10.0,
      'Audience chairs cushioned': 20.0,
      'VIP Chairs': 50.0,
      'Sofa': 150.0,
      'Deepak Stand': 25.0,
      'Center table': 30.0,
      'Rectangle table': 40.0,
      'Round tables': 35.0,
      'Flowers': 15.0,
      'Flowerpots with flowers': 12.0,
      'Flower decoration': 25.0,
      'Bokeh': 20.0,
      'Wrapped roses': 18.0,
      'Flowers bunch': 22.0,
      'Red carpet': 100.0,
      'Floor carpet': 80.0,
      'Transport (Goods)': 250.0,
      'Transport (Passenger)': 300.0,
    },
    'vendor_2': {
      'Podium': 110.0,
      'Mic and Sound System': 210.0,
      'Stage': 520.0,
      'Audience chairs non cushioned': 12.0,
      'Audience chairs cushioned': 22.0,
      'VIP Chairs': 55.0,
      'Sofa': 160.0,
      'Deepak Stand': 27.0,
      'Center table': 32.0,
      'Rectangle table': 42.0,
      'Round tables': 37.0,
      'Flowers': 16.0,
      'Flowerpots with flowers': 13.0,
      'Flower decoration': 27.0,
      'Bokeh': 22.0,
      'Wrapped roses': 20.0,
      'Flowers bunch': 24.0,
      'Red carpet': 110.0,
      'Floor carpet': 85.0,
      'Transport (Goods)': 260.0,
      'Transport (Passenger)': 310.0,
    },
    'vendor_3': {
      'Podium': 95.0,
      'Mic and Sound System': 190.0,
      'Stage': 480.0,
      'Audience chairs non cushioned': 9.0,
      'Audience chairs cushioned': 18.0,
      'VIP Chairs': 45.0,
      'Sofa': 140.0,
      'Deepak Stand': 23.0,
      'Center table': 28.0,
      'Rectangle table': 38.0,
      'Round tables': 34.0,
      'Flowers': 14.0,
      'Flowerpots with flowers': 11.0,
      'Flower decoration': 23.0,
      'Bokeh': 18.0,
      'Wrapped roses': 17.0,
      'Flowers bunch': 20.0,
      'Red carpet': 95.0,
      'Floor carpet': 75.0,
      'Transport (Goods)': 240.0,
      'Transport (Passenger)': 290.0,
    },
    // Add more vendors
  };

  // Simulated user equipment requests
  static List<EquipmentRequest> userRequests = [];
}
